# Generated by Django 5.0.6 on 2024-08-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=True, upload_to='flower/images'),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
