# Generated by Django 5.0.6 on 2024-09-04 15:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_remove_review_reviewer_review_image_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='flower/images'),
        ),
    ]
