# Generated by Django 5.0.6 on 2024-09-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_alter_flower_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
