# Generated by Django 5.0.6 on 2024-09-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_alter_flower_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
