# Generated by Django 5.0.6 on 2024-09-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustomer', '0002_coustomer_balance_deposite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='image',
            field=models.ImageField(default=False, upload_to='coustomer/image/'),
        ),
    ]
