# Generated by Django 5.0.6 on 2024-08-25 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coustomer', '0001_initial'),
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('cancel', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.flowercolor')),
                ('coustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coustomer.coustomer')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.flower')),
            ],
        ),
    ]
