# Generated by Django 5.0.6 on 2024-08-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
    ]
